    
baseURL = "https://afermg.github.io/"
languageCode = "en-uk"
title = "Alán's blog"
theme = "quasimorphic"
titleCaseStyle = "none"

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html']


[markup.goldmark.renderer]
  unsafe = true

[menu]
main = [
  {identifier = "About", name = "About", url = "/about/"},
  {identifier = "CV", name = "CV", url = "https://raw.githubusercontent.com/afermg/afermg.github.io/refs/heads/gh-pages/static/cv/cv.pdf"},
  {identifier = "Categories", name = "Categories", url = "/categories/"},
  {identifier = "Archive", name = "Archive", url = "/archive/"},
  {identifier = "RSS", name = "RSS", url = "index.xml"},
  {identifier = "Search", name = "Search", url = "/search/"},
  {identifier = "Source", name = "Source", url = "https://github.com/afermg/afermg.github.io"},
  {identifier = "Tags", name = "Tags", url = "/tags/"},
]

[taxonomies]
tag = 'tags'
categories = 'categories'

[params]
socialIcons = [
  {name = "github", url = "https://github.com/afermg"},
  {name = "rss", url = "index.xml"},
]
author = "Alán F. Muñoz"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services.rss]
  limit = 20  # Limits the feed to the 20 most recent posts
