#+TITLE: About page
#+OPTIONS: toc:nil ^:nil
#+EXPORT_FILE_NAME: ../content/about.md

* About me
I am a computational biologist with software engineering chops working of the interface of ML/DL and biology. I build tools for high throughput biological data and then use them to generate new discoveries. I am interested in interpretable AI for mechanistic understanding of biology and its drug discovery applications.

Currently, I have a postdoc role at Anne Carpenter and Shantanu Singh's Lab, at the Broad Institute of MIT and Harvard.

On a personal level, I enjoy multi-day hikes, bikepacking trips and, more recently, I got into board games.

* My current projects
- [[https://github.com/afermg/cp_measure][cp_measure]]: Featurise objects in images (microscopy or otherwise).
- [[file:github.com/afermg/nahual][nahual]]: Transfer data between environments for dependency-free deployment of complex models and algorithms.
- The Imaging platform [[https://github.com/broadinstitute/monorepo][monorepo]]: A collection of tools used by the Broad Institute's Imaging platform.
- [[file:github.com/afermg/aliby][aliby]]: End-to-end processing of high throughput microscopy time lapses.
- [[https://github.com/afermg/nix-configs][Nix Config]]: Fully reproducible computing environments for both multi-user workstations/servers and a personal Macbook.

