#+TITLE: About page
#+OPTIONS: toc:nil ^:nil
#+EXPORT_FILE_NAME: ../content/about.md

* About me
I am a computational biologist with software engineering chops working at the interface of ML/DL and biology. I develop computational tools for high throughput biological data and then use them to further my understanding of cell behaviour. I am particularly interested in interpretable AI for mechanistic understanding of biology and its applications on drug discovery, though I also enjoy learning about a wide array of topics in math and the computational/natural sciences.

Currently I have a postdoc role at the Carpenter-Singh Lab, in the Broad Institute of MIT and Harvard.

Outside work, I enjoy multi-day hikes, bikepacking trips and, more recently, I got into board games (especially worker placement/engine building ones such as [[https://boardgamegeek.com/boardgame/196340/yokohama][Yokohama]] or [[https://boardgamegeek.com/boardgame/266192/wingspan][Wingspan]]).

* Current projects
- [[https://github.com/afermg/cp_measure][cp_measure]]: Featurise objects from images and masks (microscopy or otherwise).
- [[file:github.com/afermg/nahual][nahual]]: Transfer data between running Python instances  for dependency-free deployment of complex models and algorithms (mostly deep learning models).
- The Imaging platform [[https://github.com/broadinstitute/monorepo][monorepo]]: A collection of tools used by the Broad Institute's Imaging platform.
- [[file:github.com/afermg/aliby][aliby]]: End-to-end processing of high throughput microscopy time lapses.
- [[https://github.com/afermg/nix-configs][Nix Config]]: Fully reproducible computing environments for both multi-user workstations/servers and my Macbook.

