#+hugo_base_dir: ../
#+toc: headlines 1

* Not exported                                                     :noexport:
** A portable approach to distribute image-based results
*** Introducion
A common challenge when we produce scientific results is making them available to others. There are multiple ways of doing this, sorted based on effort it takes to produce:
- No data is available.
- Data is available on a public repository
- Data and code are available, but code needs an environment to be reproduced.
- Data and code are available and packed together, and the code is available
- A portal for data exploration is available (but this needs to be hosted and maintained).
  
*** Problems
- In the case of biology, many
- The usual problems of deploying
- 
  
*** Solution
**** Tool chain
  - parquet
  - Datasette lite
  - Python to generate results
**** Solution

** Using OpenCV on Python to overlay fluorescence and bright field images
- I usually want to present a dye in live cell painting on top of bright field
  - Bright field shown as black and white
  - Fluorescence as one of the RGB colours
** Beamer presentations with animations via org-mode
- I have had to present videos of cells
- I produce everything using org-mode->LaTeX (Beamer) -> PDF
  #+begin_example LaTeX
  \animategraphics
  #+end_example
- MacOS's preview does not produce animation
 - Adobe Acrobat: 500Mb
 - Okular:
   - One must activate forms
   
** They eat sugar, don't they?
A post about how drug discovery research overlooks metabolism.
** Hive parquets on duckdb                      :@script:duckdb:datascience:
- Problem: Tables that match other tables, some nested
- Solution: Produce parquets in a hive partitions and map them using their key columns/nested directory

  This gets us the best of both worlds, the speed and out of memory computation of duckdb without the need of unnecessary row-vs-row comparisons (via JOIN)
** MAP type in DuckDB                           :@script:duckdb:datascience:
- Useful as a faster replacement to expensive JOIN 
** DuckDB vs polars

I have found Duckdb to be generally more performant than polars when used end-to-end (with no intermediate conversion to Python objects). That said, there are certain cases where I have found myself in the need of using polars.

UDF vs lambda in polars.
*** Operations where DuckDB struggles but Polars makes it easy
- Renaming columns dynamically
- Selecting columns based on data type
- Partition datasets: Converting one data frame into multiple ones based on a condition.
- Exclusion columns by id: We want all columns except for a few, and we want to select these by a numerical index.
- Concatenation (TABLE UNION)
- Loading parquet files by list (instead of by wildcard)
- Conversion to parquet can be tricky
  
** Sequence of problems and solutions:
1. Inconsistent folder structures for assays and batches.
   Generated a dictionary that defines the necessary parameters for each combination of assay and batch.
1. No available CellProfiler measurements
   Developed cp_measure to obtain the features from within python
2. Cellpose was unfriendly to multithreading
3. Dependency frailty across a multitude of tools
   Developed Nahual to transfer parameters and data across Python environments.
4. Aggregate data
   Duckdb to create databases and access them immediately
5. Run quality controls
   Marimo notebooks
   
** Setting up atuin in a new computer using nix
- What is atuin
- Why it was giving trouble
- You need to use the base64.
  
** Agenix secrets via flakes
- Make note of the steps and what I actually copied

** Nixifying DINOv2 for fine-tuning :nix:deeplearning:python:awk:@post:noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: nixifying-dinov2-for-fine-tuning
:END:
*** Getting inference working
*** Getting training working
- reusing microbiology's fixes

** Duckdb for the MBTA public dataset :duckdb:datascience:@workflow:opendata:
:PROPERTIES:
:header-args:duckdb: :session test_session :db test.duckdb :exports both
:EXPORT_FILE_NAME: duckdb-exploration-mbta
:END:

To showcase the real-life usefulness of [[https://duckdb.org/][Duckdb]] (and SQL-adjacent Domain Specific Languages in general) I decided to use the public [[https://mbta-massdot.opendata.arcgis.com/][datasets]] made available the Massachusets Bay Transport Authority (MBTA). I have lived in Boston for a couple of years and wanted to test if my intuition of the busy lines and stations lined up with their data.

There are multiple available (tabular) datasets:
- Ridership by Trip, Route line and stop
- Montly ridership by month
- Gated station entries
- Passenger surveys

#+begin_src sql :session test_session :db test.duckdb :exports both
  INSTALL httpfs;
  LOAD httpfs;

  CREATE OR REPLACE TABLE monthly_ridership AS (SELECT * FROM read_csv('https://hub.arcgis.com/api/v3/datasets/a2d15ddd86b34867a31cd4b8e0a83932_0/downloads/data?format=csv&spatialRefId=4326&where=1%3D1'));
  
  SELECT column_name, column_type FROM (DESCRIBE monthly_ridership);
#+END_SRC

#+RESULTS:
#+begin_example
┌─────────────────────────────────┬──────────────────────────┐
│           column_name           │       column_type        │
│             varchar             │         varchar          │
├─────────────────────────────────┼──────────────────────────┤
│ service_date                    │ TIMESTAMP WITH TIME ZONE │
│ mode                            │ VARCHAR                  │
│ route_or_line                   │ VARCHAR                  │
│ total_monthly_weekday_ridership │ BIGINT                   │
│ average_monthly_weekday_ridersh │ BIGINT                   │
│ countofdates_weekday            │ BIGINT                   │
│ total_monthly_ridership         │ DOUBLE                   │
│ average_monthly_ridership       │ BIGINT                   │
│ countofdates                    │ BIGINT                   │
│ ObjectId                        │ BIGINT                   │
├─────────────────────────────────┴──────────────────────────┤
│ 10 rows                                          2 columns │
└────────────────────────────────────────────────────────────┘
#+end_example

  We first loaded the =httpfs= extension to pull the data direectly from their website. I am using a local database but this should also work without writing into file thatnks to the [[https://duckdb.org/docs/stable/connect/overview][in-memory]] database capabilities of duckdb.

  Then we created a new table =montly_ridership= by running a subquery (another valid expression surrounded curly brackets). This will download and save the CSV table into a table in the database (in-memory or into a file that works as a database).

  Lastly, we describe the table and I like to filter out other columns that are not informative. I predominantly care about the column names and data types. Here the ones we care about are either =total_monthly_weekday_ridership= or =average_monthly_weekday_ridership= alongside =route_or_line=.

We will thus group by route or line to see which routes move around the 
#+begin_src sql :session test_session :db test.duckdb :exports both
  SELECT route_or_line, CAST(MEAN(total_monthly_weekday_ridership) AS INTEGER) AS mean_weekly_ridership FROM monthly_ridership GROUP BY route_or_line ORDER BY mean_weekly_ridership DESC;
#+END_SRC

#+RESULTS:
#+begin_example
┌───────────────┬───────────────────────┐
│ route_or_line │ mean_weekly_ridership │
│    varchar    │         int32         │
├───────────────┼───────────────────────┤
│ Bus           │               7395469 │
│ Red Line      │               5326706 │
│ Orange Line   │               4410355 │
│ Green Line    │               3893135 │
│ Commuter Rail │               2684943 │
│ Blue Line     │               1392658 │
│ Silver Line   │                724622 │
│ The RIDE      │                138221 │
│ Boat-F1       │                 66248 │
│ Boat-F3       │                 23922 │
│ Boat-F4       │                 19975 │
├───────────────┴───────────────────────┤
│ 11 rows                     2 columns │
└───────────────────────────────────────┘
#+end_example

We can see here all 5 lines of the metro system, in addition to commuter rail, buses, The RIDE (a door-to-door service for folks unable to ride the fixed routes) and a bunch of boat routes that cross the Boston Harbour.

Gated entries give info on specific entrances

#+begin_src sql :session test_session :db test.duckdb :exports both
  CREATE OR REPLACE TABLE gated_entries AS (SELECT * FROM read_csv('https://hub.arcgis.com/api/v3/datasets/001c177f07594e7c99f193dde32284c9_0/downloads/data?format=csv&spatialRefId=4326&where=1%3D1'));
  SELECT column_name, column_type FROM (DESCRIBE gated_entries);
#+END_SRC


#+begin_src sql :session test_session :db test.duckdb :exports both
  SELECT station_name,route_or_line,CAST(SUM(gated_entries) AS INT) AS gated_entries FROM gated_entries GROUP BY station_name, route_or_line ORDER BY gated_entries DESC
#+END_SRC
  
* DONE Set up email hosting and a personal website on personal domain :@howto:email:dns:hosting:smallweb:github:pages:
CLOSED: [2025-11-24 Mon 19:38]
:PROPERTIES:
:EXPORT_FILE_NAME: setup_email_website_personal_domain
:END:
At some point I was struggling to get access to my Gmail account. Since I usually block unwanted scripts from running on my computer, Google likes to flag my Gmail login attempts as suspicious activity. This would be fine if it didn't also make one of my only alternative identification methods an SMS. If I were to lose my phone or number I could be locked out of my account. Most accounts I have assume I have access to this email, thus a good chunk of modern life requires me accessing it, the prospect of becoming unable to log in seems quite realistic. [[https://www.migadu.com/blog/gmail/][This]] post (by an email-hosting company) builds a case against Gmail ground of privacy. It was at last time to get my own domain and control over my email. I also started this blog this year and it is pleasing to give it a nice =.com= home.

*** 'Yer a domain, Harry
Buy a domain from a domain provider. Common options are CloudFare, GoDaddy and NameCheap. I used CloudFare due to mixed comments online about customer service on the others. Also, NameCheap [[https://news.ycombinator.com/item?id=44134152][may]] pre-purchase domains that were looked up on domain search engines. If you are paranoid like me you can use [[https://tracker.debian.org/pkg/whois][whois]] (though it is being [[https://www.icann.org/en/announcements/details/icann-update-launching-rdap-sunsetting-whois-27-01-2025-en][sunset]], I'd suggest looking for an alternative). Once you find a domain name you like and is available just pay for it, you can get it for up to 10-years at a time.
    
*** Buy email hosting services and link them to the domain
Doing some research (mostly HackerNews and Reddit comments) I narrowed down options to either [[https://migadu.com/][Migadu]] and [[https://mxroute.com/][MXroute]]. =Migadu= had a free trial, so  I gave it a shot, but in the end I went for =MXroute= due to a promo they had at the time.

Make an email account. On Migadu it should be straightforward. In the case of =MXroute=, you have to pay at this point. the URL for management should be =<SERVER>.mxrouting.net:2222=, were =<SERVER>= is in the confirmation email. Once you have access to your email hosting server you can to link it to your domain.
**** Link email service to domain
  The first step once you have an account is to add DNS (Domain Name Service) records to the website. They are instructions stored in servers that provide information about how to handle requests, mostly linking names to IPs.
***** Migadu
- Export the BIND records into a file and download it
- Load this file, add them CloudFare DNS records
- If the =DKMS= and =ARC= keys fail, make sure to untoggle the =proxy= switch on their records
***** MXroute
Mostly follow the [[https://gist.github.com/afermg/69df5d99ddc7e1201b471aa6eb564e51][instructions]] sent upon registration, but it is basically the same as Migadu but without the import/export convenience. For instance, one of the MX records (with different fields separated by commas) is =MX, <domain.com>, <server>.mxrouting.net=. The ones I had to copy over from the email were:
- TXT records: =spf1= and =DKIM1=
- MX records: =<SERVER>.mxrouting.net= and =<SERVER>-relay.mxrouting.net=

  Copy them on Cloudfare, specifically on DNS records:
#+begin_example
   Cloudfare's domain home -> DNS Records -> Add record
#+end_example

**** Test the setup
- Log-in to yor account on =webmail.migadu.com= or =<SERVER>.mxrouting.net/roundcube=
- Create an account for your first user
- Send an mail to yourself to validate that it works
**** Optional: Set subdomain for server access
To access my email from my phone's Thunderbird App I had to set a subdomain. Only =MXroute= required this.
- From the Control panel provided by =MXroute= the verification key
  #+begin_example
  <SERVER>.mxrouting.net -> (sidebar) Account manager -> DNS record
  #+end_example
 And add it as a TXT record on CloudFare
- Add =mail.<domain.com>=  and/or =webmail.<domain.com>= subdomain(s) on CloudFare
  
*** Link Github Pages website to domain
If we have one, we can also link our website to the domain. Some companies like to use =blog.<domain.com>= for blogs and keep =<domain.com>= for their landing page, but since I am almost certainly a person I skipped the subdomain approach (and used the so-called apex domain). In my case I am using Github to host my website, so I followed their [[https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site][instructions]]:

1. Go to DNS records
    #+begin_example
   Cloudfare's domain home -> DNS Records -> Add record
    #+end_example
2. Add =A= records to CloudFare (e.g., =A,<domain.com>,<185.ipv4.github.address>=)
3. Add =CNAME,www,<user>.github.io= record. This step wasn't specified on the Github docs but I found it to be necessary for some reason.it
4. Add cloudfare rules to redirect https
    #+begin_example
   Cloudfare's domain home -> Cloudfare rules -> Templates -> Redirect http to HTTPS -> Deploy
    #+end_example
5. Add custom domain to github pages:
   #+begin_example
   Github repo -> settings -> pages on side panel -> Custom domain
   #+end_example
6. Also on Github, the =Enforce HTTPS= checkbox, if the rest was properly configured it should work without a hitch

*** Conclusions
I like that I have control over my email, and I could even give my family and friends their personal emails (if any of them actually wants one). The first time I did all this it took me around three hours, mostly because Github could not find my DNS records. Since I have my domain now I can probably do more fun stuff, such as self-hosting tools to share with friends and family.

* DONE Use dired-do-shell to explore the parquet schema from Emacs :@til:emacs:dired:duckdb:
CLOSED: [2025-10-23 Thu 15:21]
:PROPERTIES:
:EXPORT_FILE_NAME: emacs_dired_do_shell_duckdb
:END:

I use =dired-do-shell= command in Emacs to run CLI commands from within its file manager [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][dired]]. This workflow makes it easy to perform batch operations on files that would be annoying otherwise. The trouble arose when trying to use the =duckdb= CLI to print the schema of a parquet file, as the notation for wildcards in emacs (=*= and =?=) conflicts with duckdb's usage of the former. Thus running the following after =M-x dired-do-shell= (bound to =!= in =dired-mode=) did not work:

#+begin_src shell :eval never
duckdb -c "DESCRIBE * FROM read_parquet('?')"
#+end_src

I am trying to get Emacs to substitute =?= for the selected file(s) in dired and retain =*= as a normal duckdb wildcard (for which it means "get all columns"), but Emacs interprets the star as a wildcard and not the question mark. Thus Emacs yapped about it:

#+begin_quote
dired-do-shell-command: You can not combine ‘*’ and ‘?’ substitution marks
#+end_quote

The trick is that we need to surround =?= with backquotes (=`=), otherwise the spaces will be in the file name that =read_parquet= ingests. To fix the "naked star" problem (which Emacs will try to substitute) we can envelop it with the =COLUMNS()= command, and the lack of spaces around =*= will prevent Emacs from substituting its value. Thus the following command in the Emacs command line does the trick:

#+begin_src shell :eval never
  duckdb -c "DESCRIBE COLUMNS(*) FROM read_parquet('`?`')"
#+end_src

Which is a bit verbose but I can easily reuse from my command history to explore the schemas or parquets without leaving the dired buffer.

* DONE Calculate the cumulative sum of a column using DuckDB :@script:duckdb:datascience:gnuplot:dataviz:terminal_viz:
CLOSED: [2025-10-22 Wed 20:34]
:PROPERTIES:
:header-args:duckdb: :session duckdb_cumsum :exports both
:EXPORT_FILE_NAME: duckdb_cumsum
:END:
:LOGBOOK:
- State "DONE"       from              [2025-10-22 Wed 20:34]
:END:

Duckdb, the (tabular) data exploration tool I use supports window operations. I recently discovered that it can also perform cumulative sums in a very efficient manner.

Let us generate a toy dataset where we want to calculate the sum of one column relative to the order of another one.

#+begin_src sql :session duckdb_cumsum :exports both :results verbatim :wrap example
   -- seeding for reproducibility,  creating a table to hide output
  CREATE OR REPLACE TABLE seed AS SELECT SETSEED(0.1);

  -- Create a mock dataset with two integer columns
  CREATE OR REPLACE TABLE my_table AS
  SELECT
      #1 AS column_1,
      CAST(FLOOR(RANDOM() * 100) AS INT) AS column_2
  FROM generate_series(1, 10);  -- This generates 10 rows
  SELECT * FROM my_table;

  -- We write it to a csv for future use
  COPY my_table TO my_table.csv;
#+END_SRC 

#+RESULTS:
#+begin_example
┌──────────┬──────────┐
│ column_1 │ column_2 │
│  int64   │  int32   │
├──────────┼──────────┤
│        1 │       27 │
│        2 │       45 │
│        3 │        2 │
│        4 │       84 │
│        5 │       84 │
│        6 │       26 │
│        7 │       18 │
│        8 │       65 │
│        9 │       97 │
│       10 │       11 │
├──────────┴──────────┤
│ 10 rows   2 columns │
└─────────────────────┘
#+end_example

If we wanted to calculate the distribution of the cumulative sum of the table we could use the =OVER= clause to perform the sum of =column_2= in the order defined by =column_1=.

#+begin_src sql :session duckdb_cumsum :exports both :results verbatim :wrap example
SELECT *, sum(column_2) OVER (ORDER by column_1) AS cumulative_sum FROM my_table
#+end_src

#+RESULTS:
#+begin_example
┌──────────┬──────────┬────────────────┐
│ column_1 │ column_2 │ cumulative_sum │
│  int64   │  int32   │     int128     │
├──────────┼──────────┼────────────────┤
│        1 │       27 │             27 │
│        2 │       45 │             72 │
│        3 │        2 │             74 │
│        4 │       84 │            158 │
│        5 │       84 │            242 │
│        6 │       26 │            268 │
│        7 │       18 │            286 │
│        8 │       65 │            351 │
│        9 │       97 │            448 │
│       10 │       11 │            459 │
├──────────┴──────────┴────────────────┤
│ 10 rows                    3 columns │
└──────────────────────────────────────┘
#+end_example

The cumulative sum can be pretty handy to get a general notion of a distribution. As a bonus tip, I'll show how to use duckdb in a one-liner to plot the data
 directly in a terminal by using [[https://gnuplotting.org/][gnuplot]].
#+BEGIN_SRC shell :exports both :results verbatim
  duckdb -csv -c "
      SELECT *, sum(column_2) OVER (ORDER by column_1) AS cumulative_sum
      FROM read_csv('my_table.csv');" |
      gnuplot -e "
      set terminal dumb;
      set datafile separator ',';
      set style data histograms;
      set style fill solid 1.00 border -1;
      set xlabel 'Column 1';
      set ylabel 'CSum';
      set title 'Cumulative Sum of values';
      plot '-' using 3:xtic(1);" |
      tr -d '\014' # Remove a pesky ^L at the top
#+END_SRC

#+RESULTS:
#+begin_example
                                                                               
                                                                               
                              Cumulative Sum of values                         
     500 +-----------------------------------------------------------------+   
         |          +     +    +     +    +     +    +     +    +    ++    |   
     450 |-+                                   '-' using 3:xtic+-+ +-||--+-|   
     400 |-+                                                   |#|   ||  +-|   
         |                                                     |#|   ||    |   
     350 |-+                                              ++   |#|   ||  +-|   
         |                                                ||   |#|   ||    |   
     300 |-+                                        +-+   ||   |#|   ||  +-|   
     250 |-+                                   ++   |#|   ||   |#|   ||  +-|   
CSum     |                               +-+   ||   |#|   ||   |#|   ||    |   
     200 |-+                             |#|   ||   |#|   ||   |#|   ||  +-|   
         |                               |#|   ||   |#|   ||   |#|   ||    |   
     150 |-+                        ++   |#|   ||   |#|   ||   |#|   ||  +-|   
         |                          ||   |#|   ||   |#|   ||   |#|   ||    |   
     100 |-+                  +-+   ||   |#|   ||   |#|   ||   |#|   ||  +-|   
      50 |-+             ++   |#|   ||   |#|   ||   |#|   ||   |#|   ||  +-|   
         |         +-+   ||   |#|   ||   |#|   ||   |#|   ||   |#|   ||    |   
       0 +-----------------------------------------------------------------+   
                    1     2    3     4    5     6    7     8    9    10        
                                      Column 1                                 
                                                                               
#+end_example

We get a cute ascii-like plot! That is a bit too long of a "one-liner", I'll go through the commands:
- Run a =duckdb= command (=-c=) that reads the previously-saved table. The =-csv= flag at the starts converts the output to csv.
- Run gnuplot with certain specifications:
  - The flag =-e= Allows to pass a series of commands without an interactive session.
  - =set terminal dumb=: it will send as plain text to stdout.
  - =set datafiler separator ","=: The input is a CSV file.
  - =set style data histograms=: Changes the plotting style into a barplot.
  - =set style fill solid ...=: Visual adjustments to the bars for clarity.
  - =set xlabel ...= Adds the axis labels. Similar for =ylabel= and =title=.
  - =plot '-' using 3:xtic(1)=: Use stdin data to Plot the columns 3 on the y axis (=cumulative_sum=) and the first column in the x-axis (=column_1=).
- Lastly, use the =tr= command line tool to remove a =^L= That appeared at the start of the output and was bothering me too much.

  
  While there are a many other ways to wrangle tables such as via pandas or polars in Python, I find duckdb to be a powerful tool for exploratory analyses and data wrangling (often from within Python). It is flexible enough to be used by itself, via bindings in another language, or directly on the command line. Lastly, I showed that when used as a Command Line Interface (CLI) duckdb synergises with other tools for data visualisation from the comfort(?) of the terminal.
  
* DONE Run multiple python scripts in the background :@script:screen:nahual:shell:nix:
CLOSED: [2025-08-26 Tue 14:29]
:PROPERTIES:
:EXPORT_FILE_NAME: screen-batch-model-deployment
:END:
:LOGBOOK:
- State "DONE"       from              [2025-08-26 Tue 14:29]
:END:

To solve a multitude of challenges I have faced when processing high throughput microscopy data, have developed [[https://github.com/afermg/nahual][Nahual]], a tool that allows me to move data across multiple Python environments that deploy deep learning models in the background. I usually keep these models "listening" in the background for the main analysis pipeline ([[https://github.com/afermg/aliby][aliby]]) to send them data to process. To be able to monitor what's going on inside of these scripts I use [[https://www.gnu.org/software/screen/][GNU screen]], which allows me to detach and reattach into these sessions whenever I need to. At some point I had to reboot my server and had rerun all these in independent screens. This rudimentary shell script did the job:

#+begin_src shell
  cd cellpose
  screen -d -S cellpose1 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose1.ipc"'
  screen -d -S cellpose2 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose2.ipc"'
  cd ../trackastra
  screen -d -S trackastra -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/trackastra.ipc"'
  cd ..
#+end_src

Basically the screen runs my Nix environment and deploys the model (in this case, my [[https://github.com/afermg/nahual][fork]] of cellpose with Nix dependency management) while detached. This executes a =server.py= file within the Nix enviroment, it runs on a loop waiting to receive data and process it. Automatically deploying to multiple screens reduces the annoyance of having to the usual steps of (go to the folder -> run screen -> Nix environment -> run Python server -> Detach screen session). I just add more models if I want further deployments, put it in a bash script and call it a day.

To access any of these screens for inspection I just use the name indicated after the =-S= flag (e.g., =screen -r cellpose1=). This way I can check if any issue crops up in the main analysis script or pipeline.

* DONE Simple progress indicators with awk           :@script:awk:find:watch:
CLOSED: [2025-08-19 Tue 18:58]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-simple-progress-indicator
:END:
I wanted a simple way to see the progress of a data processing pipeline, and the internal progress bar tools were messed up by threading. I thus decided to use the number of output files in each folder as an indicator of progress. In my case the output of =tree .= looks like this:

#+begin_example
.
└── steps
    ├── A01_001
    │   ├── segment_nuclei
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...
    │   │   └── 0019.npz
    │   ├── tile
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...

#+end_example

I can get the info I need by counting the total number of files and the occurrences of the =A01_001= -> =P24_005= range (these are fields of view from a microscopy experiment). Using this simple =find= command we get all the files in the current folder.

#+begin_src bash
find . -type f
#+end_src

which results in this:

#+begin_example
./steps: 
./steps/A01_003/tile/0007.npz
./steps/A01_003/tile/0009.npz
./steps/A01_003/tile/0018.npz
./steps/A01_003/tile/0016.npz
...
#+end_example

We could use =wc -l= to get the number of files per directory, we want a bunch of progress bars to get a better sense of change over time. For this I use =awk=, my swiss-army knife for text processing, and I write a short script that counts, [[https://stackoverflow.com/a/2458455][sorts]] and [[https://stackoverflow.com/a/68371463][prints]] the number of occurrences as a number of dots. I also added a conditional to only track after more than one file has been produced, for pipelines that produce save one file before actually running the whole pipeline.

#+begin_src awk
  # progress_bar.awk
  {
      if (match($0,"([A-P][0-9]{2}_[0-9]{3})", capture)){
  	count[capture[1]] += 1
      }
      
  }
  END{
      n=asorti(count, sorted)
      for (i=1; i<=n; i++){
  	nfiles = count[sorted[i]]
  	if (nfiles > 1){
  	    s = sprintf(key "%*s", nfiles, "");
  	    gsub(".", ".", s)
  	    print sorted[i] " " s
  	}
      }
  }
#+end_src

Running the =find= command and the =awk= script (=find . -type f | awk -f progress_bar.awk=) yields the following snapshot of the processing progess

#+begin_example
A01_001 ...............................................................
A01_002 ...............................................................
A01_003 ...............................................................
A01_004 ...............................................................
A01_005 ...............................................................
A02_001 ...............................................................
A02_002 ...............................................................
A02_003 .................................................
A02_004 ..........................................
A02_005 ........................................
A03_001 ..............................................
#+end_example

Thus the last thing to do is to use `watch` to automatically refresh the status:

=watch -dc --interval 1 'find . -type f | awk -f progress_bar.awk | tac'=

The =watch=  flag =-d= highlight the changes over time and =-c= enables intrepreting ANSI colours, in my terminal this makes the changes last stay longer, but YMMV. Finally, =tac= makes sure that the last lines are displayed at the top. I like to run this command somewhere in another terminal or in a `screen` terminal multiplexer. When the number of rows becomes too high it may be useful find a heuristic to remove uninformative lines.

* DONE Update figure numbering                      :@script:awk:textediting:
CLOSED: [2025-08-14 Thu 15:42]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-update-figure-numbering
:END:

I was editing some markdown and had to insert a new figure in the middle. The problem is that this document already has an explicit figure numbering (e.g., "Figure 5"), so changing tens of figures felt dull. I like to run small (GNU) =awk= scripts for this type of tasks.

#+begin_src awk
  # update_figures.awk
  {
      if (match($0, "Figure ([0-9]+)", num)){
  	   if (num[1] > after)
  	       gsub("Figure ([0-9]+)", "Figure " num[1] + increase_by)
      };
      print $0
  }
#+end_src

This changes Figure =X=  into Figure =X= + =increase_by= starting after the variable "after".  And we can run it as follows:

#+begin_src shell
awk -v after=4 -v increase_by=1 -f update_figures.awk input_file.md
#+end_src

To edit the file in-place add the =-i= flag.

* DONE Recursive search and replace      :@til:ripgrep:oneliner:textediting:
CLOSED: [2025-08-12 Tue 13:07]
:PROPERTIES:
:EXPORT_FILE_NAME: recursive-search-replace
:END:
I needed to rename all occurrences of a pattern with another, where I knew there was no ambiguous situations. This uses =ripgrep=, =xargs= and =GNU sed=. [[https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#search-and-replace][source]].

#+begin_src shell
rg old_pattern --files-with-matches | xargs sed -i 's/old_pattern/new_pattern/g'
#+end_src

* DONE Github code review on existing code base     :@til:github:code:review:
CLOSED: [2024-11-26 Tue 13:06]
:PROPERTIES:
:EXPORT_FILE_NAME: github-review-existing-code
:END:

  Create an empty branch with one empty commit
  1. Create new branch =git checkout --orphan review-1-target=
  2. Reset =git reset .=
  3. Clean branch =git clean -df=
  4. Add empty commit =git commit --allow-empty -m 'Empty commit'=
     
  Rebase a branch to put this commit at the root
  5. Push to your fork =git push -u origin review-1-target=
  6. Move to branch to review =git checkout origin/main=
  7. Spin-off branch from here =git checkout -b review-1=
  8. Rebase to empty branch =git rebase -i review-1-target=, the empty commit must be at the start
  9. Push =git push -u origin review-1=

  That should make a pull request possible, providing the code review tooling.
  [[https://thib.me/recipe-code-reviews-for-existing-code-with-github][source]]
* DONE A workflow for bioimaging and data exploration :@post:marimo:dataviz:tools:demo:
CLOSED: [2025-07-30 Wed 13:05]
:PROPERTIES:
:EXPORT_FILE_NAME: marimo-for-bioimage-exploration
:END:
One of the common challenges when analysing large bioimaging datasets is to bring it all together in one place. I usually use tools like [[https://duckdb.org/][DuckDB]] for database querying and [[https://github.com/cytomining/copairs][copairs]] for selecting statistically significant subsets of the data. For one of my recent projects I built a [[https://github.com/marimo-team/marimo][marimo]] interface to explore the result of large-scale (~2TB images, ~2GB feature profiles) image-based profiles, then performs dimensionality reduction of the data, and finally retrieves back the images. This I think is the ideal workflow, one where you can be nimble and pull up the images alongside statistical analyses to be able to interpret the data structure in the biological context. The code is not yet available to the public, but you can find the demo [[https://drive.google.com/file/d/1t2ygATiJ2r0GPkeEwdw6FqHZxoOwQmzW/view][here]]. 

* My ox-hugo setup                                                 :noexport:
