#+hugo_base_dir: ../
#+toc: headlines 1

* DONE Calculate the cumulative sum of a column using DuckDB :@script:duckdb:datascience:gnuplot:dataviz:terminal_viz:
CLOSED: [2025-10-22 Wed 20:34]
:PROPERTIES:
:header-args:duckdb: :session duckdb_cumsum :exports both
:EXPORT_FILE_NAME: duckdb_cumsum
:END:
:LOGBOOK:
- State "DONE"       from              [2025-10-22 Wed 20:34]
:END:

Duckdb, the (tabular) data exploration tool I use supports window operations. I recently discovered that it can also perform cumulative sums in a very efficient manner.

Let us generate a toy dataset where we want to calculate the sum of one column relative to the order of another one.

#+BEGIN_SRC duckdb :session duckdb_cumsum :exports both :results verbatim :wrap example
  CREATE OR REPLACE TABLE seed AS SELECT SETSEED(0.1); -- seeding for reproducibility,  creating a table to hide output

  -- Create a mock dataset with two integer columns
  CREATE OR REPLACE TABLE my_table AS
  SELECT
      #1 AS column_1,
      CAST(FLOOR(RANDOM() * 100) AS INT) AS column_2
  FROM generate_series(1, 10);  -- This generates 10 rows
  SELECT * FROM my_table;

  -- We write it to a csv for future use
  COPY my_table TO my_table.csv;
#+END_SRC 

#+RESULTS:
#+begin_example
┌──────────┬──────────┐
│ column_1 │ column_2 │
│  int64   │  int32   │
├──────────┼──────────┤
│        1 │       27 │
│        2 │       45 │
│        3 │        2 │
│        4 │       84 │
│        5 │       84 │
│        6 │       26 │
│        7 │       18 │
│        8 │       65 │
│        9 │       97 │
│       10 │       11 │
├──────────┴──────────┤
│ 10 rows   2 columns │
└─────────────────────┘
#+end_example

If we wanted to calculate the distribution of the cumulative sum of the table we could use the =OVER= clause to perform the sum of =column_2= in the order defined by =column_1=.

#+begin_src duckdb :session duckdb_cumsum :exports both :results verbatim :wrap example
SELECT *, sum(column_2) OVER (ORDER by column_1) AS cumulative_sum FROM my_table
#+end_src

#+RESULTS:
#+begin_example
┌──────────┬──────────┬────────────────┐
│ column_1 │ column_2 │ cumulative_sum │
│  int64   │  int32   │     int128     │
├──────────┼──────────┼────────────────┤
│        1 │       27 │             27 │
│        2 │       45 │             72 │
│        3 │        2 │             74 │
│        4 │       84 │            158 │
│        5 │       84 │            242 │
│        6 │       26 │            268 │
│        7 │       18 │            286 │
│        8 │       65 │            351 │
│        9 │       97 │            448 │
│       10 │       11 │            459 │
├──────────┴──────────┴────────────────┤
│ 10 rows                    3 columns │
└──────────────────────────────────────┘
#+end_example

The cumulative sum can be pretty handy to get a general notion of a distribution. As a bonus tip, I'll show how to use duckdb in a one-liner to plot the data
 directly in a terminal by using [[https://gnuplotting.org/][gnuplot]].
#+BEGIN_SRC shell :exports both :results verbatim
  duckdb -csv -c "SELECT *, sum(column_2) OVER (ORDER by column_1) AS cumulative_sum FROM read_csv('my_table.csv');" |
      gnuplot -e "
      set terminal dumb;
      set datafile separator ',';
      set style data histograms;
      set style fill solid 1.00 border -1;
      set xlabel 'Column 1';
      set ylabel 'CSum';
      set title 'Cumulative Sum of values';
      plot '-' using 3:xtic(1);" |
      tr -d '\014' # Remove a pesky ^L at the top
#+END_SRC

#+RESULTS:
#+begin_example
                                                                               
                                                                               
                              Cumulative Sum of values                         
     500 +-----------------------------------------------------------------+   
         |          +     +    +     +    +     +    +     +    +    ++    |   
     450 |-+                                   '-' using 3:xtic+-+ +-||--+-|   
     400 |-+                                                   |#|   ||  +-|   
         |                                                     |#|   ||    |   
     350 |-+                                              ++   |#|   ||  +-|   
         |                                                ||   |#|   ||    |   
     300 |-+                                        +-+   ||   |#|   ||  +-|   
     250 |-+                                   ++   |#|   ||   |#|   ||  +-|   
CSum     |                               +-+   ||   |#|   ||   |#|   ||    |   
     200 |-+                             |#|   ||   |#|   ||   |#|   ||  +-|   
         |                               |#|   ||   |#|   ||   |#|   ||    |   
     150 |-+                        ++   |#|   ||   |#|   ||   |#|   ||  +-|   
         |                          ||   |#|   ||   |#|   ||   |#|   ||    |   
     100 |-+                  +-+   ||   |#|   ||   |#|   ||   |#|   ||  +-|   
      50 |-+             ++   |#|   ||   |#|   ||   |#|   ||   |#|   ||  +-|   
         |         +-+   ||   |#|   ||   |#|   ||   |#|   ||   |#|   ||    |   
       0 +-----------------------------------------------------------------+   
                    1     2    3     4    5     6    7     8    9    10        
                                      Column 1                                 
                                                                               
#+end_example

We get a cute ascii-like plot! That is a bit too long of a "one-liner", I'll go through what went in:
- Run a =duckdb= command (=-c=) that reads the previously-saved table. The =-csv= flag at the starts converts the output to csv.
- Run gnuplot with certain specifications:
  - The flag =-e= Allows to pass a series of commands without an interactive session.
  - =set terminal dumb=: it will send as plain text to stdout.
  - =set datafiler separator ","=: The input is a CSV file.
  - =set style data histograms=: CMakes the output a barplot.
  - =set xlabel ...= Adds the axis labels. Similar for =ylabel= and =title=.
  - =plot '-' using 3:xtic(1)=: Use stdin data to Plot the columns 3 on the y axis (=cumulative_sum=) and the first column in the x-axis (=column_1=).
- Lastly, use the =tr= command line tool to remove a =^L= That appeared at the start of the output and was bothering me too much.

  While there are a many other ways to wrangle tables such as via pandas or polars in Python, I find duckdb to be a powerful tool for exploratory analyses and data wrangling (often from within Python). It is flexible enough to be used by itself, within another language such as Python or directly on the command line. I have also shown that when used as a Command Line Interface (CLI) duckdb synergises with other tools for data visualisation on the comfort(?) of the terminal.
  
* DONE Run multiple python scripts in the background :@script:screen:nahual:shell:nix:
CLOSED: [2025-08-26 Tue 14:29]
:PROPERTIES:
:EXPORT_FILE_NAME: screen-batch-model-deployment
:END:
:LOGBOOK:
- State "DONE"       from              [2025-08-26 Tue 14:29]
:END:

To solve a multitude of challenges I have faced when processing high throughput microscopy data, have developed [[https://github.com/afermg/nahual][Nahual]], a tool that allows me to move data across multiple Python environments that deploy deep learning models in the background. I usually keep these models "listening" in the background for the main analysis pipeline ([[https://github.com/afermg/aliby][aliby]]) to send them data to process. To be able to monitor what's going on inside of these scripts I use [[https://www.gnu.org/software/screen/][GNU screen]], which allows me to detach and reattach into these sessions whenever I need to. At some point I had to reboot my server and had rerun all these in independent screens. This rudimentary shell script did the job:

#+begin_src shell
  cd cellpose
  screen -d -S cellpose1 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose1.ipc"'
  screen -d -S cellpose2 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose2.ipc"'
  cd ../trackastra
  screen -d -S trackastra -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/trackastra.ipc"'
  cd ..
#+end_src

Basically the screen runs my Nix environment and deploys the model (in this case, my [[https://github.com/afermg/nahual][fork]] of cellpose with Nix dependency management) while detached. This executes a =server.py= file within the Nix enviroment, it runs on a loop waiting to receive data and process it. Automatically deploying to multiple screens reduces the annoyance of having to the usual steps of (go to the folder -> run screen -> Nix environment -> run Python server -> Detach screen session). I just add more models if I want further deployments, put it in a bash script and call it a day.

To access any of these screens for inspection I just use the name indicated after the =-S= flag (e.g., =screen -r cellpose1=). This way I can check if any issue crops up in the main analysis script or pipeline.

* DONE Simple progress indicators with awk           :@script:awk:find:watch:
CLOSED: [2025-08-19 Tue 18:58]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-simple-progress-indicator
:END:
I wanted a simple way to see the progress of a data processing pipeline, and the internal progress bar tools were messed up by threading. I thus decided to use the number of output files in each folder as an indicator of progress. In my case the output of =tree .= looks like this:

#+begin_example
.
└── steps
    ├── A01_001
    │   ├── segment_nuclei
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...
    │   │   └── 0019.npz
    │   ├── tile
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...

#+end_example

I can get the info I need by counting the total number of files and the occurrences of the =A01_001= -> =P24_005= range (these are fields of view from a microscopy experiment). Using this simple =find= command we get all the files in the current folder.

#+begin_src bash
find . -type f
#+end_src

which results in this:

#+begin_example
./steps: 
./steps/A01_003/tile/0007.npz
./steps/A01_003/tile/0009.npz
./steps/A01_003/tile/0018.npz
./steps/A01_003/tile/0016.npz
...
#+end_example

We could use =wc -l= to get the number of files per directory, we want a bunch of progress bars to get a better sense of change over time. For this I use =awk=, my swiss-army knife for text processing, and I write a short script that counts, [[https://stackoverflow.com/a/2458455][sorts]] and [[https://stackoverflow.com/a/68371463][prints]] the number of occurrences as a number of dots. I also added a conditional to only track after more than one file has been produced, for pipelines that produce save one file before actually running the whole pipeline.

#+begin_src awk
  # progress_bar.awk
  {
      if (match($0,"([A-P][0-9]{2}_[0-9]{3})", capture)){
  	count[capture[1]] += 1
      }
      
  }
  END{
      n=asorti(count, sorted)
      for (i=1; i<=n; i++){
  	nfiles = count[sorted[i]]
  	if (nfiles > 1){
  	    s = sprintf(key "%*s", nfiles, "");
  	    gsub(".", ".", s)
  	    print sorted[i] " " s
  	}
      }
  }
#+end_src

Running the =find= command and the =awk= script (=find . -type f | awk -f progress_bar.awk=) yields the following snapshot of the processing progess

#+begin_example
A01_001 ...............................................................
A01_002 ...............................................................
A01_003 ...............................................................
A01_004 ...............................................................
A01_005 ...............................................................
A02_001 ...............................................................
A02_002 ...............................................................
A02_003 .................................................
A02_004 ..........................................
A02_005 ........................................
A03_001 ..............................................
#+end_example

Thus the last thing to do is to use `watch` to automatically refresh the status:

=watch -dc --interval 1 'find . -type f | awk -f progress_bar.awk | tac'=

The =watch=  flag =-d= highlight the changes over time and =-c= enables intrepreting ANSI colours, in my terminal this makes the changes last stay longer, but YMMV. Finally, =tac= makes sure that the last lines are displayed at the top. I like to run this command somewhere in another terminal or in a `screen` terminal multiplexer. When the number of rows becomes too high it may be useful find a heuristic to remove uninformative lines.

* DONE Update figure numbering                      :@script:awk:textediting:
CLOSED: [2025-08-14 Thu 15:42]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-update-figure-numbering
:END:

I was editing some markdown and had to insert a new figure in the middle. The problem is that this document already has an explicit figure numbering (e.g., "Figure 5"), so changing tens of figures felt dull. I like to run small (GNU) =awk= scripts for this type of tasks.

#+begin_src awk
  # update_figures.awk
  {
      if (match($0, "Figure ([0-9]+)", num)){
  	   if (num[1] > after)
  	       gsub("Figure ([0-9]+)", "Figure " num[1] + increase_by)
      };
      print $0
  }
#+end_src

This changes Figure =X=  into Figure =X= + =increase_by= starting after the variable "after".  And we can run it as follows:

#+begin_src shell
awk -v after=4 -v increase_by=1 -f update_figures.awk input_file.md
#+end_src

To edit the file in-place add the =-i= flag.

* DONE Recursive search and replace      :@til:ripgrep:oneliner:textediting:
CLOSED: [2025-08-12 Tue 13:07]
:PROPERTIES:
:EXPORT_FILE_NAME: recursive-search-replace
:END:
I needed to rename all occurrences of a pattern with another, where I knew there was no ambiguous situations. This uses =ripgrep=, =xargs= and =GNU sed=. [[https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#search-and-replace][source]].

#+begin_src shell
rg old_pattern --files-with-matches | xargs sed -i 's/old_pattern/new_pattern/g'
#+end_src

* DONE Github code review on existing code base     :@til:github:code:review:
CLOSED: [2024-11-26 Tue 13:06]
:PROPERTIES:
:EXPORT_FILE_NAME: github-review-existing-code
:END:

  Create an empty branch with one empty commit
  1. Create new branch =git checkout --orphan review-1-target=
  2. Reset =git reset .=
  3. Clean branch =git clean -df=
  4. Add empty commit =git commit --allow-empty -m 'Empty commit'=
     
  Rebase a branch to put this commit at the root
  5. Push to your fork =git push -u origin review-1-target=
  6. Move to branch to review =git checkout origin/main=
  7. Spin-off branch from here =git checkout -b review-1=
  8. Rebase to empty branch =git rebase -i review-1-target=, the empty commit must be at the start
  9. Push =git push -u origin review-1=

  That should make a pull request possible, providing the code review tooling.
  [[https://thib.me/recipe-code-reviews-for-existing-code-with-github][source]]
* DONE A workflow for bioimaging and data exploration :@post:marimo:dataviz:tools:demo:
CLOSED: [2025-07-30 Wed 13:05]
:PROPERTIES:
:EXPORT_FILE_NAME: marimo-for-bioimage-exploration
:END:
One of the common challenges when analysing large bioimaging datasets is to bring it all together in one place. I usually use tools like [[https://duckdb.org/][DuckDB]] for database querying and [[https://github.com/cytomining/copairs][copairs]] for selecting statistically significant subsets of the data. For one of my recent projects I built a [[https://github.com/marimo-team/marimo][marimo]] interface to explore the result of large-scale (~2TB images, ~2GB feature profiles) image-based profiles, then performs dimensionality reduction of the data, and finally retrieves back the images. This I think is the ideal workflow, one where you can be nimble and pull up the images alongside statistical analyses to be able to interpret the data structure in the biological context. The code is not yet available to the public, but you can find the demo [[https://drive.google.com/file/d/1t2ygATiJ2r0GPkeEwdw6FqHZxoOwQmzW/view][here]]. 

* Not exported                                                     :noexport:

