#+hugo_base_dir: ../
#+toc: headlines 1
* Nixifying DINOv2 for fine-tuning :nix:deeplearning:python:awk:@post:noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: nixifying-dinov2-for-fine-tuning
:END:
** Getting inference working
** Getting training working
- reusing microbiology's fixes

* DONE Deploy multiple models in the background :@script:screen:nahual:shell:nix:
CLOSED: [2025-08-26 Tue 14:29]
:PROPERTIES:
:EXPORT_FILE_NAME: screen-batch-model-deployment
:END:
:LOGBOOK:
- State "DONE"       from              [2025-08-26 Tue 14:29]
:END:

To solve a multitude of challenges I have faced when processing high throughput microscopy data, have developed [[https://github.com/afermg/nahual][Nahual]], a tool that allows me to move data across multiple Python environments that deploy deep learning models in the background. I usually keep these models "listening" in the background for the main analysis pipeline ([[https://github.com/afermg/aliby][aliby]]) to send them data to process. To be able to monitor what's going on inside of these scripts I use [[https://www.gnu.org/software/screen/][GNU screen]], which allows me to detach and reattach into these sessions whenever I need to. At some point I had to reboot my server and had rerun all these in independent screens. This rudimentary shell script did the job:

#+begin_src shell
  cd cellpose
  screen -d -S cellpose2 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose2.ipc"'
  screen -d -S cellpose1 -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/cellpose1.ipc"'
  cd ../trackastra
  screen -d -S trackastra -m bash -c 'nix develop . --command bash -c "python server.py ipc:///tmp/trackastra.ipc"'
  cd ..
#+end_src

Basically the screen runs my Nix environment and deploys the model (in this case, my [[github.com/afermg/cellpose][fork]] of cellpose with Nix dependency management) while detached. This executes a =server.py= file within the Nix enviroment, it runs on a loop waiting to receive data and process it. Automatically deploying to multiple screens reduces the annoyance of having to the usual steps of (go to the folder -> run screen -> Nix environment -> run Python server -> Detach screen session). I just add more models if I want further deployments, put it in a bash script and call it a day.

To access any of these screens for inspection I just use the name indicated after the =-S= flag (e.g., =screen -r cellpose1=). This way I can check if any issue crops up in the main analysis script or pipeline.

* DONE Simple progress indicators with awk           :@script:awk:find:watch:
CLOSED: [2025-08-19 Tue 18:58]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-simple-progress-indicator
:END:
I wanted a simple way to see the progress of a data processing pipeline, and the internal progress bar tools were messed up by threading. I thus decided to use the number of output files in each folder as an indicator of progress. In my case the output of =tree .= looks like this:

#+begin_example
.
└── steps
    ├── A01_001
    │   ├── segment_nuclei
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...
    │   │   └── 0019.npz
    │   ├── tile
    │   │   ├── 0000.npz
    │   │   ├── 0001.npz
    │   │   ├── ...

#+end_example

I can get the info I need by counting the total number of files and the occurrences of the =A01_001= -> =P24_005= range (these are fields of view from a microscopy experiment). Using this simple =find= command we get all the files in the current folder.

#+begin_src bash
find . -type f
#+end_src

which results in this:

#+begin_example
./steps: 
./steps/A01_003/tile/0007.npz
./steps/A01_003/tile/0009.npz
./steps/A01_003/tile/0018.npz
./steps/A01_003/tile/0016.npz
...
#+end_example

We could use =wc -l= to get the number of files per directory, we want a bunch of progress bars to get a better sense of change over time. For this I use =awk=, my swiss-army knife for text processing, and I write a short script that counts, [[https://stackoverflow.com/a/2458455][sorts]] and [[https://stackoverflow.com/a/68371463][prints]] the number of occurrences as a number of dots. I also added a conditional to only track after more than one file has been produced, for pipelines that produce save one file before actually running the whole pipeline.

#+begin_src awk
  # progress_bar.awk
  {
      if (match($0,"([A-P][0-9]{2}_[0-9]{3})", capture)){
  	count[capture[1]] += 1
      }
      
  }
  END{
      n=asorti(count, sorted)
      for (i=1; i<=n; i++){
  	nfiles = count[sorted[i]]
  	if (nfiles > 1){
  	    s = sprintf(key "%*s", nfiles, "");
  	    gsub(".", ".", s)
  	    print sorted[i] " " s
  	}
      }
  }
#+end_src

Running the =find= command and the =awk= script (=find . -type f | awk -f progress_bar.awk=) yields the following snapshot of the processing progess

#+begin_example
A01_001 ...............................................................
A01_002 ...............................................................
A01_003 ...............................................................
A01_004 ...............................................................
A01_005 ...............................................................
A02_001 ...............................................................
A02_002 ...............................................................
A02_003 .................................................
A02_004 ..........................................
A02_005 ........................................
A03_001 ..............................................
#+end_example

Thus the last thing to do is to use `watch` to automatically refresh the status:

=watch -dc --interval 1 'find . -type f | awk -f progress_bar.awk | tac'=

The =watch=  flag =-d= highlight the changes over time and =-c= enables intrepreting ANSI colours, in my terminal this makes the changes last stay longer, but YMMV. Finally, =tac= makes sure that the last lines are displayed at the top. I like to run this command somewhere in another terminal or in a `screen` terminal multiplexer. When the number of rows becomes too high it may be useful find a heuristic to remove uninformative lines.

* DONE Update figure numbering                      :@script:awk:textediting:
CLOSED: [2025-08-19 Tue 15:42]
:PROPERTIES:
:EXPORT_FILE_NAME: awk-update-figure-numbering
:END:

I was editing some markdown and had to insert a new figure in the middle. The problem is that this document already has an explicit figure numbering (e.g., "Figure 5"), so changing tens of figures felt dull. I like to run small (GNU) =awk= scripts for this type of tasks.

#+begin_src awk
  # update_figures.awk
  {
      if (match($0, "Figure ([0-9]+)", num)){
  	   if (num[1] > after)
  	       gsub("Figure ([0-9]+)", "Figure " num[1] + increase_by)
      };
      print $0
  }
#+end_src

This changes Figure =X=  into Figure =X= + =increase_by= starting after the variable "after".  And we can run it as follows:

#+begin_src shell
awk -v after=4 -v increase_by=1 -f update_figures.awk input_file.md
#+end_src

To edit the file in-place add the =-i= flag.

* DONE Recursive search and replace      :@til:ripgrep:oneliner:textediting:
CLOSED: [2025-08-12 Tue 13:07]
:PROPERTIES:
:EXPORT_FILE_NAME: recursive-search-replace
:END:
I needed to rename all occurrences of a pattern with another, where I knew there was no ambiguous situations. This uses =ripgrep=, =xargs= and =GNU sed=. [[https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#search-and-replace][source]].

#+begin_src shell
rg old_pattern --files-with-matches | xargs sed -i 's/old_pattern/new_pattern/g'
#+end_src

* DONE Github code review on existing code base     :@til:github:code:review:
CLOSED: [2024-11-26 Tue 13:06]
:PROPERTIES:
:EXPORT_FILE_NAME: github-review-existing-code
:END:

  Create an empty branch with one empty commit
  1. Create new branch =git checkout --orphan review-1-target=
  2. Reset =git reset .=
  3. Clean branch =git clean -df=
  4. Add empty commit =git commit --allow-empty -m 'Empty commit'=
     
  Rebase a branch to put this commit at the root
  5. Push to your fork =git push -u origin review-1-target=
  6. Move to branch to review =git checkout origin/main=
  7. Spin-off branch from here =git checkout -b review-1=
  8. Rebase to empty branch =git rebase -i review-1-target=, the empty commit must be at the start
  9. Push =git push -u origin review-1=

  That should make a pull request possible, providing the code review tooling.
  [[https://thib.me/recipe-code-reviews-for-existing-code-with-github][source]]
* DONE A workflow for bioimaging and data exploration :@post:marimo:dataviz:tools:demo:
CLOSED: [2025-07-30 Wed 13:05]
:PROPERTIES:
:EXPORT_FILE_NAME: marimo-for-bioimage-exploration
:END:
One of the common challenges when analysing large bioimaging datasets is to bring it all together in one place. I usually use tools like [[https://duckdb.org/][DuckDB]] for database querying and [[https://github.com/cytomining/copairs][copairs]] for selecting statistically significant subsets of the data. For one of my recent projects I built a [[https://github.com/marimo-team/marimo][marimo]] interface to explore the result of large-scale (~2TB images, ~2GB feature profiles) image-based profiles, then performs dimensionality reduction of the data, and finally retrieves back the images. This I think is the ideal workflow, one where you can be nimble and pull up the images alongside statistical analyses to be able to interpret the data structure in the biological context. The code is not yet available to the public, but you can find the demo [[https://drive.google.com/file/d/1t2ygATiJ2r0GPkeEwdw6FqHZxoOwQmzW/view][here]]. 

* Not exported                                                     :noexport:

