#+TITLE: Blog
#+hugo_base_dir: ./

* Technical blog
*** A workflow for bioimaging and data exploration
One of the common challenges when analysing large bioimaging datasets is to bring it all together in one place. Internally using tools like [[https://duckdb.org/][DuckDB]] for database querying and [[https://github.com/cytomining/copairs][copairs]] for selecting statistically significant subsets of the data. For one of my recent projects I built a [[https://github.com/marimo-team/marimo][marimo]] interface to explore the result of large-scale (~2TB images, ~2GB feature profiles) image-based profiles, then performs dimensionality reduction of the data, and finally retrieves back the images. This I think is the ideal workflow, one where you can be nimble and pull up the images alongside statistical analyses to be able to interpret the data structure in the biological context. The code is not yet available to the public, but you can find the demo [[https://drive.google.com/file/d/1t2ygATiJ2r0GPkeEwdw6FqHZxoOwQmzW/view][here]]. 
